services:
  - type: web
    name: centrum-ozs-iwonki
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeployTrigger: commit
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
